function createBaseUser(overrides = {}) {
  return {
    userId: "user1",
    welcomeColumnsAndTask: false,
    chartPreferences: {
      timeRangeType: "week",
      taskType: "active",
      chartType: "bar",
      xAxisField: "day",
      yAxisMetric: "count",
      sortOrder: "none",
      dueFilter: "both",
      priorityFilters: [],
      dayOfWeekFilters: [],
      statusFilters: [],
      assignedToFilter: "",
      minTaskCount: "",
      minStoryPoints: "",
      minTimeSpent: "",
      minTimeUnit: "seconds",
      scheduledOnly: false,
      includeZeroMetrics: true,
      includeNoDueDate: true,
      comparisonMode: false,
      compStartDate: null,
      compEndDate: null,
      customStartDate: null,
      customEndDate: null,
    },
    settingsPreferences: {
      darkMode: true,
      muteNotifications: false,
      inactivityTimeoutHours: 1,
      inactivityTimeoutNever: true,
      defaultPriority: "A1",
      hideOldCompletedTasksDays: 365,
      hideOldCompletedTasksNever: true,
      defaultBoardView: "boards",
      disableToCreateTask: false,
      confirmBeforeDeleteTask: true,
      confirmBeforeDeleteBoard: true,
      notifyNonPriorityGoesOvertime: 1,
      notifyScheduledTaskIsDue: 5,
      themeAccent: "Green",
      topbarAccent: "Blue",
    },
    lastWeeklyNotification: null,
    ...overrides,
  };
}

module.exports = { createBaseUser };
