function createBaseUser(overrides = {}) {
  return {
    userId: "user1",
    name: "User",
    profilePicture: "",
    welcomeColumnsAndTask: false,
    labels: [],
    chartPreferences: {
      timeRangeType: "week",
      taskType: "active",
      chartType: "bar",
      xAxisField: "day",
      yAxisMetric: "count",
      sortOrder: "none",
      dueFilter: "both",
      priorityFilters: [],
      labelFilters: [],
      includeNoneLabel: false,
      dayOfWeekFilters: [],
      statusFilters: [],
      assignedToFilter: "",
      minTaskCount: "",
      minStoryPoints: "",
      minTimeSpent: "",
      minTimeUnit: "seconds",
      scheduledOnly: false,
      includeZeroMetrics: true,
      includeNoDueDate: true,
      comparisonMode: false,
      compStartDate: null,
      compEndDate: null,
      customStartDate: null,
      customEndDate: null,
    },
    settingsPreferences: {
      darkMode: true,
      muteNotifications: false,
      inactivityTimeoutHours: 24,
      inactivityTimeoutNever: true,
      defaultPriority: "A1",
      hideOldCompletedTasksDays: 365,
      hideOldCompletedTasksNever: true,
      defaultBoardView: "boards",
      disableToCreateTask: false,
      confirmBeforeDeleteTask: true,
      confirmBeforeDeleteBoard: true,
      notifyNonPriorityGoesOvertime: 1,
      notifyScheduledTaskIsDue: 5,
      themeAccent: "Green",
      themeAccentCustom: "",
      topbarAccent: "Blue",
      topbarAccentCustom: "",
      priorityColours: {
        A1: "#ff4d4d",
        A2: "#ff6666",
        A3: "#ff9999",
        B1: "#4d4dff",
        B2: "#6666ff",
        B3: "#9999ff",
        C1: "#4dff4d",
        C2: "#66ff66",
        C3: "#99ff99",
        D: "#cc66ff",
        E: "#ff9966",
      },
    },
    lastWeeklyNotification: null,
    ...overrides,
  };
}

module.exports = { createBaseUser };
